### ISSUE TITLE
Remove `--include-paths` and `--exclude-paths` in v3.0

### ISSUE THREAD

**Issue by tarkatronic** [godaddy/tartufo#255] opened 2021-11-02 20:27 UTC
## Is your feature request related to a problem? Please describe.

The `-i` / `--include-paths` and `-x` / `--exclude-paths` options have been deprecated since v2.5.0 and should be removed.

## Describe the solution you'd like

`-i` / `--include-paths` and `-x` / `--exclude-paths` options are completely removed.

**Comment by emayuri-godaddy** [comment] 2021-11-10 17:05
The issue is addressed in https://github.com/godaddy/tartufo/pull/276

**Closed as completed by emayuri-godaddy** 2021-11-10 17:05 UTC
Labels: enhancement
