### ISSUE TITLE
Pre-commit appears to be missing new finds

### ISSUE THREAD

**Issue by mxhenry-godaddy** [godaddy/tartufo#185] opened 2021-04-15 20:16 UTC
## To Reproduce

1. Add to a git workflow yml file `actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6`
2. Run `tartufo pre-commit`
3. Observe no findings
4. Commit
5. Run `tartufo scan-local-repo --max-depth 100 . `
6. Observe the following finding (or similar)

```bash
~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~
Reason: High Entropy
Filepath: .github/workflows/tartufo_pr.yml
Signature: 45789f58aee4394d13e82c73c4f725dfeefdd120d7c50d89b4431ef15605d529
Commit time: 2021-04-15 13:01:23
Commit message: <snip>

<snip>
-      - name: Checkout GoDaddy Actions Tartufo repo
-        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
+      - name: Set up Python 3.8
+        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
         with:
<snip>
```

## Expected Behavior

`pre-commit` produces the same finding as the `scan-local-repo`

## Code Example

See repro

## Environment

tartufo 2.4 on macOS Catalina on Python 3.8.9

**Comment by pmevzek-godaddy** [comment] 2021-05-25 17:48
BTW if that help, I can't reproduce the problem with the data above:

```
$ git init test
$ cd test/
$ mkdir -p .github/workflows/
$ vi .github/workflows/tartufo_pr.yml
$ cat .github/workflows/tartufo_pr.yml
Yes I know it is a fake one,
just taking it out of the issue example

      - name: Set up Python 3.8
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6
         with:
$ git add .github/workflows/tartufo_pr.yml
$ tartufo --json --entropy --regex pre-commit | jq .
{
  "scan_time": "2021-05-25T12:47:42.607317",
  "project_path": "/private/tmp/test",
  "output_dir": null,
  "excluded_paths": [],
  "excluded_signatures": [],
  "found_issues": [
    {
      "file_path": ".github/workflows/tartufo_pr.yml",
      "matched_string": "dc73133d4da04e56a135ae2246682783cc7c7cb6",
      "signature": "45789f58aee4394d13e82c73c4f725dfeefdd120d7c50d89b4431ef15605d529",
      "issue_type": "High Entropy",
      "issue_detail": null,
      "diff": "@@ -0,0 +1,6 @@\n+Yes I know it is a fake one,\n+just taking it out of the issue example\n+\n+      - name: Set up Python 3.8\n+        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6\n+         with:\n"
    }
  ]
}
```

With:
```
$ tartufo --version
tartufo, version 2.4.0
$ python3 --version
Python 3.8.5
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1030

**Comment by tarkatronic** [comment] 2021-08-12 21:42
@mxhenry-godaddy When you encountered this issue, had you staged the files for commit, with `git add`? It's worth noting that the `pre-commit` mode only scans files which are currently staged for commit, and this is by design. Also, given that the `pre-commit` mode is designed to be run specifically in the environment of a git pre-commit hook, I'm not certain that running it as a command outside of that environment will actually behave as expected.

**Comment by mxhenry-godaddy** [comment] 2021-08-25 15:18
Sorry, I really don't remember. If I had to guess under duress I would say they probably were not staged.

**Comment by tarkatronic** [comment] 2021-10-19 18:21
I'm going to close this issue for now as we cannot verify it, and it appears that it _may_ be behaving as intended.

In case any users are able to replicate this behavior in the future, please open a new issue, along with steps to reproduce.

**Closed as completed by tarkatronic** 2021-10-19 18:21 UTC
Labels: bug
